bench: bench.o timer.o random.o RCconfig.o
	gcc -O -pg -g bench.o timer.o random.o RCconfig.o -o bench -ldbst 

CL=	${CC} -O -pg -g -c 

bench.o: 
	$(CL)  bench.c -o bench.o -I../include -I../PORT/include -I../util

timer.o: 
	$(CL) ../util/timer.c -o timer.o -I../util

random.o: 
	$(CL) ../util/random.c -o random.o 

RCconfig.o: 
	$(CL) ../util/RCconfig.c -o RCconfig.o -I../util


